name: Cloudflared
version: 5.1.13
slug: cloudflared
description: Use a Cloudflare Tunnel to remotely connect to Home Assistant without
  opening any ports
url: https://github.com/brenner-tobias/addon-cloudflared/
codenotary: dev@brenner.tech
init: false
hassio_api: true
privileged:
- NET_ADMIN
- NET_RAW
hassio_role: homeassistant
arch:
- aarch64
- amd64
- armv7
map:
- addon_config:rw
options:
  external_hostname: ''
  additional_hosts: []
schema:
  external_hostname: str?
  additional_hosts:
  - hostname: str
    service: str
    disableChunkedEncoding: bool?
  tunnel_name: str?
  catch_all_service: str?
  nginx_proxy_manager: bool?
  tunnel_token: str?
  post_quantum: bool?
  run_parameters:
  - match(^(--edge-bind-address|--edge-ip-version|--grace-period|--ha-connections|--logfile|--loglevel|--pidfile|--protocol|--region|--retries|--tag)=.*$)?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
image: ghcr.io/brenner-tobias/cloudflared/{arch}
init_commands:
- apk add iptables
- iptables -F
- iptables -A OUTPUT -d 192.168.0.111 -p tcp --dport 8099 -j ACCEPT
- iptables -A OUTPUT -d 192.168.0.111 -p tcp --sport 8099 -j ACCEPT
- iptables -A INPUT -s 192.168.0.111 -p tcp --dport 8099 -j ACCEPT
- iptables -A INPUT -s 192.168.0.111 -p tcp --sport 8099 -j ACCEPT
- iptables -A OUTPUT -d 192.168.0.0/24 -j DROP
- iptables -A OUTPUT -d 172.30.33.0/24 -j DROP
- iptables -A INPUT -s 192.168.0.0/24 -j DROP
- iptables -A INPUT -s 172.30.33.0/24 -j DROP
